"""Add Course Task and File models

Revision ID: 386b4b309695
Revises: e41c88d07229
Create Date: 2026-05-26 01:57:30.516153

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '386b4b309695'
down_revision = 'e41c88d07229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
