"""Add Course Task and File models

Revision ID: 42d0acd10c57
Revises: 219b5d8a99a4
Create Date: 2026-05-26 00:59:18.177807

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '42d0acd10c57'
down_revision = '219b5d8a99a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
