"""File table update

Revision ID: 7f55da77affd
Revises: b26ef8a6e79e
Create Date: 2026-05-27 01:26:59.835848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f55da77affd'
down_revision = 'b26ef8a6e79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
