"""File table update

Revision ID: 8cf663eb5543
Revises: 7f55da77affd
Create Date: 2026-05-27 01:41:47.464522

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8cf663eb5543'
down_revision = '7f55da77affd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'data')
    # ### end Alembic commands ###
