"""Add user-course link table

Revision ID: b26ef8a6e79e
Revises: 386b4b309695
Create Date: 2026-05-26 02:01:02.941291

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b26ef8a6e79e'
down_revision = '386b4b309695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
