/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTaskRouteImport } from './routes/_layout/task'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCoursesRouteRouteImport } from './routes/_layout/courses/route'
import { Route as LayoutCoursesIndexRouteImport } from './routes/_layout/courses/index'
import { Route as LayoutCoursesCourseIdRouteRouteImport } from './routes/_layout/courses/$courseId/route'
import { Route as LayoutCoursesCourseIdIndexRouteImport } from './routes/_layout/courses/$courseId/index'
import { Route as LayoutCoursesCourseIdTasksRouteRouteImport } from './routes/_layout/courses/$courseId/tasks/route'
import { Route as LayoutCoursesCourseIdTasksIndexRouteImport } from './routes/_layout/courses/$courseId/tasks/index'
import { Route as LayoutCoursesCourseIdTasksTaskIdRouteRouteImport } from './routes/_layout/courses/$courseId/tasks/$taskId/route'
import { Route as LayoutCoursesCourseIdTasksTaskIdIndexRouteImport } from './routes/_layout/courses/$courseId/tasks/$taskId/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskRoute = LayoutTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesRouteRoute = LayoutCoursesRouteRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesIndexRoute = LayoutCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCoursesRouteRoute,
} as any)
const LayoutCoursesCourseIdRouteRoute =
  LayoutCoursesCourseIdRouteRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => LayoutCoursesRouteRoute,
  } as any)
const LayoutCoursesCourseIdIndexRoute =
  LayoutCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutCoursesCourseIdRouteRoute,
  } as any)
const LayoutCoursesCourseIdTasksRouteRoute =
  LayoutCoursesCourseIdTasksRouteRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => LayoutCoursesCourseIdRouteRoute,
  } as any)
const LayoutCoursesCourseIdTasksIndexRoute =
  LayoutCoursesCourseIdTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutCoursesCourseIdTasksRouteRoute,
  } as any)
const LayoutCoursesCourseIdTasksTaskIdRouteRoute =
  LayoutCoursesCourseIdTasksTaskIdRouteRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => LayoutCoursesCourseIdTasksRouteRoute,
  } as any)
const LayoutCoursesCourseIdTasksTaskIdIndexRoute =
  LayoutCoursesCourseIdTasksTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutCoursesCourseIdTasksTaskIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/courses': typeof LayoutCoursesRouteRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/task': typeof LayoutTaskRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdRouteRouteWithChildren
  '/courses/': typeof LayoutCoursesIndexRoute
  '/courses/$courseId/tasks': typeof LayoutCoursesCourseIdTasksRouteRouteWithChildren
  '/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/courses/$courseId/tasks/$taskId': typeof LayoutCoursesCourseIdTasksTaskIdRouteRouteWithChildren
  '/courses/$courseId/tasks/': typeof LayoutCoursesCourseIdTasksIndexRoute
  '/courses/$courseId/tasks/$taskId/': typeof LayoutCoursesCourseIdTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/task': typeof LayoutTaskRoute
  '/': typeof LayoutIndexRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/courses/$courseId/tasks': typeof LayoutCoursesCourseIdTasksIndexRoute
  '/courses/$courseId/tasks/$taskId': typeof LayoutCoursesCourseIdTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/courses': typeof LayoutCoursesRouteRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/task': typeof LayoutTaskRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/courses/$courseId': typeof LayoutCoursesCourseIdRouteRouteWithChildren
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
  '/_layout/courses/$courseId/tasks': typeof LayoutCoursesCourseIdTasksRouteRouteWithChildren
  '/_layout/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/_layout/courses/$courseId/tasks/$taskId': typeof LayoutCoursesCourseIdTasksTaskIdRouteRouteWithChildren
  '/_layout/courses/$courseId/tasks/': typeof LayoutCoursesCourseIdTasksIndexRoute
  '/_layout/courses/$courseId/tasks/$taskId/': typeof LayoutCoursesCourseIdTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/courses'
    | '/admin'
    | '/items'
    | '/settings'
    | '/task'
    | '/courses/$courseId'
    | '/courses/'
    | '/courses/$courseId/tasks'
    | '/courses/$courseId/'
    | '/courses/$courseId/tasks/$taskId'
    | '/courses/$courseId/tasks/'
    | '/courses/$courseId/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/task'
    | '/'
    | '/courses'
    | '/courses/$courseId'
    | '/courses/$courseId/tasks'
    | '/courses/$courseId/tasks/$taskId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/courses'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/task'
    | '/_layout/'
    | '/_layout/courses/$courseId'
    | '/_layout/courses/'
    | '/_layout/courses/$courseId/tasks'
    | '/_layout/courses/$courseId/'
    | '/_layout/courses/$courseId/tasks/$taskId'
    | '/_layout/courses/$courseId/tasks/'
    | '/_layout/courses/$courseId/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task': {
      id: '/_layout/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof LayoutTaskRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses': {
      id: '/_layout/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof LayoutCoursesIndexRouteImport
      parentRoute: typeof LayoutCoursesRouteRoute
    }
    '/_layout/courses/$courseId': {
      id: '/_layout/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LayoutCoursesCourseIdRouteRouteImport
      parentRoute: typeof LayoutCoursesRouteRoute
    }
    '/_layout/courses/$courseId/': {
      id: '/_layout/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof LayoutCoursesCourseIdIndexRouteImport
      parentRoute: typeof LayoutCoursesCourseIdRouteRoute
    }
    '/_layout/courses/$courseId/tasks': {
      id: '/_layout/courses/$courseId/tasks'
      path: '/tasks'
      fullPath: '/courses/$courseId/tasks'
      preLoaderRoute: typeof LayoutCoursesCourseIdTasksRouteRouteImport
      parentRoute: typeof LayoutCoursesCourseIdRouteRoute
    }
    '/_layout/courses/$courseId/tasks/': {
      id: '/_layout/courses/$courseId/tasks/'
      path: '/'
      fullPath: '/courses/$courseId/tasks/'
      preLoaderRoute: typeof LayoutCoursesCourseIdTasksIndexRouteImport
      parentRoute: typeof LayoutCoursesCourseIdTasksRouteRoute
    }
    '/_layout/courses/$courseId/tasks/$taskId': {
      id: '/_layout/courses/$courseId/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/courses/$courseId/tasks/$taskId'
      preLoaderRoute: typeof LayoutCoursesCourseIdTasksTaskIdRouteRouteImport
      parentRoute: typeof LayoutCoursesCourseIdTasksRouteRoute
    }
    '/_layout/courses/$courseId/tasks/$taskId/': {
      id: '/_layout/courses/$courseId/tasks/$taskId/'
      path: '/'
      fullPath: '/courses/$courseId/tasks/$taskId/'
      preLoaderRoute: typeof LayoutCoursesCourseIdTasksTaskIdIndexRouteImport
      parentRoute: typeof LayoutCoursesCourseIdTasksTaskIdRouteRoute
    }
  }
}

interface LayoutCoursesCourseIdTasksTaskIdRouteRouteChildren {
  LayoutCoursesCourseIdTasksTaskIdIndexRoute: typeof LayoutCoursesCourseIdTasksTaskIdIndexRoute
}

const LayoutCoursesCourseIdTasksTaskIdRouteRouteChildren: LayoutCoursesCourseIdTasksTaskIdRouteRouteChildren =
  {
    LayoutCoursesCourseIdTasksTaskIdIndexRoute:
      LayoutCoursesCourseIdTasksTaskIdIndexRoute,
  }

const LayoutCoursesCourseIdTasksTaskIdRouteRouteWithChildren =
  LayoutCoursesCourseIdTasksTaskIdRouteRoute._addFileChildren(
    LayoutCoursesCourseIdTasksTaskIdRouteRouteChildren,
  )

interface LayoutCoursesCourseIdTasksRouteRouteChildren {
  LayoutCoursesCourseIdTasksTaskIdRouteRoute: typeof LayoutCoursesCourseIdTasksTaskIdRouteRouteWithChildren
  LayoutCoursesCourseIdTasksIndexRoute: typeof LayoutCoursesCourseIdTasksIndexRoute
}

const LayoutCoursesCourseIdTasksRouteRouteChildren: LayoutCoursesCourseIdTasksRouteRouteChildren =
  {
    LayoutCoursesCourseIdTasksTaskIdRouteRoute:
      LayoutCoursesCourseIdTasksTaskIdRouteRouteWithChildren,
    LayoutCoursesCourseIdTasksIndexRoute: LayoutCoursesCourseIdTasksIndexRoute,
  }

const LayoutCoursesCourseIdTasksRouteRouteWithChildren =
  LayoutCoursesCourseIdTasksRouteRoute._addFileChildren(
    LayoutCoursesCourseIdTasksRouteRouteChildren,
  )

interface LayoutCoursesCourseIdRouteRouteChildren {
  LayoutCoursesCourseIdTasksRouteRoute: typeof LayoutCoursesCourseIdTasksRouteRouteWithChildren
  LayoutCoursesCourseIdIndexRoute: typeof LayoutCoursesCourseIdIndexRoute
}

const LayoutCoursesCourseIdRouteRouteChildren: LayoutCoursesCourseIdRouteRouteChildren =
  {
    LayoutCoursesCourseIdTasksRouteRoute:
      LayoutCoursesCourseIdTasksRouteRouteWithChildren,
    LayoutCoursesCourseIdIndexRoute: LayoutCoursesCourseIdIndexRoute,
  }

const LayoutCoursesCourseIdRouteRouteWithChildren =
  LayoutCoursesCourseIdRouteRoute._addFileChildren(
    LayoutCoursesCourseIdRouteRouteChildren,
  )

interface LayoutCoursesRouteRouteChildren {
  LayoutCoursesCourseIdRouteRoute: typeof LayoutCoursesCourseIdRouteRouteWithChildren
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
}

const LayoutCoursesRouteRouteChildren: LayoutCoursesRouteRouteChildren = {
  LayoutCoursesCourseIdRouteRoute: LayoutCoursesCourseIdRouteRouteWithChildren,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
}

const LayoutCoursesRouteRouteWithChildren =
  LayoutCoursesRouteRoute._addFileChildren(LayoutCoursesRouteRouteChildren)

interface LayoutRouteChildren {
  LayoutCoursesRouteRoute: typeof LayoutCoursesRouteRouteWithChildren
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTaskRoute: typeof LayoutTaskRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCoursesRouteRoute: LayoutCoursesRouteRouteWithChildren,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTaskRoute: LayoutTaskRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
